# The version tag is obsolete and has been removed.
services:
  # --- INFRASTRUCTURE SERVICES ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: myvahan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myvahan_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- APPLICATION SERVICES ---
  gateway:
    build:
      context: . # Use the project root as the "workshop"
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on: [auth-service, ride-service]
    environment:
      - AUTH_SERVICE_ADDR=auth-service:50051
      - RIDE_SERVICE_ADDR=ride-service:50052

  auth-service:
    # --- THIS FIX IS APPLIED HERE ---
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    depends_on: [kafka, postgres]
    environment:
      - DATABASE_URL=postgresql://myvahan:password@postgres:5432/myvahan_db
      - KAFKA_BROKER=kafka:9092
      - JWT_SECRET=supersecretkey
    ports:
      - "50051:50051"

  ride-service:
    build:
      context: .
      dockerfile: services/ride-service/Dockerfile
    depends_on: [kafka, postgres]
    environment:
      - DATABASE_URL=postgresql://myvahan:password@postgres:5432/myvahan_db
      - KAFKA_BROKER=kafka:9092
    ports:
      - "50052:50052"

  matching-service:
    build:
      context: .
      dockerfile: services/matching-service/Dockerfile
    depends_on: [kafka, postgres]
    environment:
      - DATABASE_URL=postgresql://myvahan:password@postgres:5432/myvahan_db
      - KAFKA_BROKER=kafka:9092

volumes:
  pgdata:
