# No version tag needed for modern Docker Compose
services:
  # --- INFRASTRUCTURE SERVICES ---

  # Zookeeper: Manages Kafka's cluster state.
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # Performance Tune: Increase the session timeout to prevent premature disconnections.
      ZOOKEEPER_SESSION_TIMEOUT: "60000"
    ports:
      - "2181:2181"

  # Kafka: The event streaming platform.
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      # Performance Tune: Increase the session timeout to match Zookeeper's.
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: "60000"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    # Robust Healthcheck: Gives Kafka ample time to start up before other services depend on it.
    healthcheck:
      test: ["CMD", "cub", "kafka-ready", "-b", "kafka:29092", "1", "20"]
      interval: 20s
      timeout: 15s
      retries: 10

  # Postgres: The relational database.
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: myvahan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myvahan_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myvahan -d myvahan_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- APPLICATION SERVICES ---

  # API Gateway: The single entry point for all external requests.
  gateway:
    build:
      context: . # Build context is the project root
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      # Waits for the services to start, not necessarily become healthy.
      auth-service: { condition: service_started }
      ride-service: { condition: service_started }

  # Auth Service: Handles all user authentication and authorization.
  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    # Waits for Kafka and Postgres to be fully 'healthy' before starting.
    depends_on:
      kafka: { condition: service_healthy }
      postgres: { condition: service_healthy }
    environment:
      - KAFKA_BROKER=kafka:29092
      - DATABASE_URL=postgresql://myvahan:password@postgres:5432/myvahan_db
      - JWT_SECRET=supersecretkey

  # Ride Service: Handles ride creation and event production.
  ride-service:
    build:
      context: .
      dockerfile: services/ride-service/Dockerfile
    depends_on:
      kafka: { condition: service_healthy }
      postgres: { condition: service_healthy }
    environment:
      - KAFKA_BROKER=kafka:29092
      - DATABASE_URL=postgresql://myvahan:password@postgres:5432/myvahan_db

  # Matching Service: Consumes ride requests and finds drivers.
  matching-service:
    build:
      context: .
      dockerfile: services/matching-service/Dockerfile
    depends_on:
      kafka: { condition: service_healthy }
      postgres: { condition: service_healthy }
    environment:
      - KAFKA_BROKER=kafka:29092
      - DATABASE_URL=postgresql://myvahan:password@postgres:5432/myvahan_db

# Named volume for persisting PostgreSQL data.
volumes:
  pgdata:
