version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: myvahan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myvahan_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build: ./services/auth-service
    depends_on: [kafka, postgres]
    environment:
      - KAFKA_BROKER=kafka:9092
      - JWT_SECRET=supersecretkey
    ports:
      - "50051:50051"

  ride-service:
    build: ./services/ride-service
    depends_on: [kafka, postgres]
    environment:
      - KAFKA_BROKER=kafka:9092
    ports:
      - "50052:50052"

volumes:
  pgdata:
